version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPassword123
    ports:
      - "1433:1433"
    networks:
      - sql_network
    restart: always
    volumes:
      - sql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "TuPassword123", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

networks:
  sql_network:
    driver: bridge

volumes:
  sql_data:
    driver: local
